<?php
namespace App\Console\Commands; use App\Library\CurlRequest; use function DeepCopy\deep_copy; use Illuminate\Console\Command; use Illuminate\Support\Str; class Update extends Command { protected $signature = 'update'; protected $description = 'check update'; public function __construct() { parent::__construct(); } private function download_progress($sp3ae187, $sp89a419) { $sp82a428 = fopen($sp89a419, 'w+'); if (!$sp82a428) { return false; } $sp4e752c = curl_init(); curl_setopt($sp4e752c, CURLOPT_URL, $sp3ae187); curl_setopt($sp4e752c, CURLOPT_FOLLOWLOCATION, true); curl_setopt($sp4e752c, CURLOPT_RETURNTRANSFER, true); curl_setopt($sp4e752c, CURLOPT_FILE, $sp82a428); curl_setopt($sp4e752c, CURLOPT_PROGRESSFUNCTION, function ($sp0571b4, $sp63dbe3, $sp67476b, $sp0958df, $sp0dc2bb) { if ($sp63dbe3 > 0) { echo '    download: ' . sprintf('%.2f', $sp67476b / $sp63dbe3 * 100) . '%'; } }); curl_setopt($sp4e752c, CURLOPT_NOPROGRESS, false); curl_setopt($sp4e752c, CURLOPT_HEADER, 0); curl_setopt($sp4e752c, CURLOPT_USERAGENT, 'card update'); curl_exec($sp4e752c); curl_close($sp4e752c); echo '
'; return true; } public function handle() { set_time_limit(0); \Artisan::call('cache:clear'); \Artisan::call('config:clear'); echo '
'; $this->comment('检查更新中...'); $this->info('当前版本: ' . config('app.version')); $sp48d343 = @json_decode(CurlRequest::get('https://github.com/Tai7sy/card-system/blob/master/.version'), true); if (!@$sp48d343['data']['version']) { $this->warn('检查更新失败!'); $this->warn('Error: ' . ((@$sp48d343['message'] ?? $sp48d343) ?? 'Network error')); goto LABEL_EXIT; } $sp48d343 = $sp48d343['data']; if (config('app.version') >= $sp48d343['version']) { $this->comment('您的版本已是最新!'); goto LABEL_EXIT; } $this->info('最新版本: ' . $sp48d343['version']); $this->info('版本说明: ' . (@$sp48d343['description'] ?? '无')); $sp7e8ab7 = strtolower($this->ask('是否现在更新 (yes/no)', 'no')); if ($sp7e8ab7 !== 'yes') { goto LABEL_EXIT; } $spcdad27 = realpath(sys_get_temp_dir()); if (strlen($spcdad27) < 3) { $this->warn('获取临时目录失败!'); goto LABEL_EXIT; } $spcdad27 .= DIRECTORY_SEPARATOR . Str::random(16); if (!mkdir($spcdad27) || !is_writable($spcdad27) || !is_readable($spcdad27)) { $this->warn('临时目录不可读写!'); goto LABEL_EXIT; } if (!function_exists('exec')) { $this->warn('函数 exec 已被禁用, 无法继续更新!'); goto LABEL_EXIT; } if (PHP_OS === 'WINNT') { $sp4eb5ef = 'C:\\Program Files\\7-Zip\\7z.exe'; if (!is_file($sp4eb5ef)) { $sp4eb5ef = strtolower($this->ask('未找到7-Zip, 请手动输入7zG.exe路径', $sp4eb5ef)); } if (!is_file($sp4eb5ef)) { $this->warn('7-Zip不可用, 请安装7-Zip后重试'); goto LABEL_EXIT; } $sp4eb5ef = '"' . $sp4eb5ef . '"'; } else { exec('tar --version', $sp245564, $spdf727a); if ($spdf727a) { $this->warn('Error: tar --version 
' . join('
', $sp245564)); goto LABEL_EXIT; } } $this->comment('正在下载新版本...'); $sp89a419 = $spcdad27 . DIRECTORY_SEPARATOR . 'ka_update_' . Str::random(16) . '.tmp'; if (!$this->download_progress($sp48d343['url'], $sp89a419)) { $this->warn('写入临时文件失败!'); goto LABEL_EXIT; } $sp318f05 = md5_file($sp89a419); if ($sp318f05 !== $sp48d343['md5']) { $this->warn('更新文件md5校验失败!, file:' . $sp318f05 . ', require:' . $sp48d343['md5']); goto LABEL_EXIT; } $this->comment('正在解压...'); unset($sp245564); if (PHP_OS === 'WINNT') { exec("{$sp4eb5ef} x -so {$sp89a419} | {$sp4eb5ef} x -aoa -si -ttar -o{$spcdad27}", $sp245564, $spdf727a); } else { exec("tar -zxf {$sp89a419} -C {$spcdad27}", $sp245564, $spdf727a); } if ($spdf727a) { $this->warn('Error: 解压失败 
' . join('
', $sp245564)); goto LABEL_EXIT; } $this->comment('正在关闭主站...'); \Artisan::call('down'); sleep(5); $this->comment(' --> 正在清理旧文件...'); $sp447462 = base_path(); foreach (array('app', 'bootstrap', 'config', 'public/dist', 'database', 'routes', 'vendor') as $spd55287) { \File::deleteDirectory($sp447462 . DIRECTORY_SEPARATOR . $spd55287); } $this->comment(' --> 正在复制新文件...'); \File::copyDirectory($spcdad27 . DIRECTORY_SEPARATOR . 'card_dist', $sp447462); $this->comment(' --> 正在创建缓存...'); \Artisan::call('cache:clear'); \Artisan::call('route:cache'); \Artisan::call('config:cache'); $this->comment(' --> 正在更新数据库...'); \Artisan::call('migrate'); if (PHP_OS === 'WINNT') { echo '
'; $this->alert('请注意手动设置目录权限'); $this->comment('    storage 可读可写             '); $this->comment('    bootstrap/cache/ 可读可写    '); echo '

'; } else { $this->comment(' --> 正在设置目录权限...'); exec('rm -rf storage/framework/cache/data/*'); exec('chmod -R 777 storage/'); exec('chmod -R 777 bootstrap/cache/'); } $this->comment('正在启用主站...'); \Artisan::call('up'); \Artisan::call('queue:restart'); $sp7d0ad5 = true; LABEL_EXIT: if (isset($spcdad27) && strlen($spcdad27) > 19) { $this->comment('清理临时目录...'); \File::deleteDirectory($spcdad27); } if (isset($sp7d0ad5) && $sp7d0ad5) { $this->info('更新成功!'); } if (PHP_OS === 'WINNT') { } else { exec('rm -rf storage/framework/cache/data/*'); exec('chmod -R 777 storage/'); exec('chmod -R 777 bootstrap/cache/'); } echo '
'; die; } }